"use client";

import { useEffect, useMemo, useState } from "react";
import { AppShell } from "@/components/shell/app-shell";
import { ProBadge, ProButton, ProCard, ProEmptyState, ProLoadingState, ProMain, ProPageHeader, ProStatCard } from "@/components/ui/pro-shell";
import { WriteDisabledHint } from "@/components/write-disabled-hint";
import { useAppStore } from "@/lib/store/use-app-store";
import { useSubscription } from "@/lib/subscription/subscription-provider";
import { useWriteAccess } from "@/lib/subscription/use-can-write";
import { fetchActiveReturnHolds, type ReturnHoldRecord } from "@/lib/supabase/return-hold-client";
import { createTextileDispatch, fetchTextileDispatches, fetchTextileFulfilmentAllocations, fetchTextileTransfers, initiateTextileTransfer, inspectTextileReturn, receiveTextileTransfer, scanTextileDispatchPick, transitionTextileDispatch, type TextileDispatch, type TextileFulfilmentAllocation, type TextileTransfer } from "@/lib/supabase/textile-warehouse-client";
import { dispatchProgress } from "@/lib/textile-warehouse-domain";

const label="text-xs font-semibold text-slate-600";
const input="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm text-slate-950 outline-none focus:border-teal-400 focus:ring-4 focus:ring-teal-100/70";
const primary="inline-flex min-h-11 items-center justify-center rounded-xl bg-teal-600 px-4 text-sm font-semibold text-white shadow-sm hover:bg-teal-700 disabled:opacity-50";
const secondary="inline-flex min-h-10 items-center justify-center rounded-xl border border-slate-200 bg-white px-3.5 text-sm font-semibold text-slate-700 shadow-sm hover:bg-slate-50 disabled:opacity-50";
const makeId=()=>crypto.randomUUID();

export default function TextileDispatchPage(){
 const{data,ready}=useAppStore();const{org}=useSubscription();const{canWrite}=useWriteAccess();
 const[allocations,setAllocations]=useState<TextileFulfilmentAllocation[]>([]);const[dispatches,setDispatches]=useState<TextileDispatch[]>([]);const[transfers,setTransfers]=useState<TextileTransfer[]>([]);const[returnHolds,setReturnHolds]=useState<ReturnHoldRecord[]>([]);const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");
 const[tab,setTab]=useState<"dispatch"|"transfer"|"returns">("dispatch");const[saleId,setSaleId]=useState("");const[selected,setSelected]=useState<Record<string,string>>({});const[customerName,setCustomerName]=useState("");const[address,setAddress]=useState("");
 const[activeId,setActiveId]=useState<string|null>(null);const[scanCode,setScanCode]=useState("");const[scanQty,setScanQty]=useState("");const[carrier,setCarrier]=useState("");const[vehicleNo,setVehicleNo]=useState("");const[tracking,setTracking]=useState("");
 const[transferRoll,setTransferRoll]=useState("");const[toLocation,setToLocation]=useState("");const[receiveCode,setReceiveCode]=useState("");
 const[returnAllocation,setReturnAllocation]=useState<Record<string,string>>({});const[returnDecision,setReturnDecision]=useState<Record<string,"reusable_remnant"|"damaged"|"rejected">>({});const[returnReason,setReturnReason]=useState<Record<string,string>>({});const[returnRollNo,setReturnRollNo]=useState<Record<string,string>>({});
 const canOperate=canWrite&&["owner","manager","data_entry"].includes(org.role);const canTransfer=canWrite&&(org.role==="owner"||org.role==="manager");
 const productById=useMemo(()=>new Map((data?.products??[]).map((p)=>[p.id,p])),[data?.products]);
 async function refresh(){if(!org.id||org.sector!=="textile"){setLoading(false);return;}setLoading(true);const[a,d,t,h]=await Promise.all([fetchTextileFulfilmentAllocations(org.id),fetchTextileDispatches(org.id),fetchTextileTransfers(org.id),fetchActiveReturnHolds(org.id)]);setLoading(false);const problem=a.error||d.error||t.error||h.error;if(problem)setError(problem);else setError("");setAllocations(a.data);setDispatches(d.data);setTransfers(t.data);setReturnHolds(h.data);}
 useEffect(()=>{void refresh();// eslint-disable-next-line react-hooks/exhaustive-deps
 },[org.id,org.sector]);
 const saleIds=Array.from(new Set(allocations.filter((a)=>a.assignedQuantity<a.quantity-.0005).map((a)=>a.saleId)));
 const saleAllocations=allocations.filter((a)=>a.saleId===saleId&&a.assignedQuantity<a.quantity-.0005);
 async function createDispatch(){if(!org.id||!canOperate||!saleId)return;const items=saleAllocations.flatMap((a)=>{const qty=Number(selected[a.id]||0);return qty>0?[{saleAllocationId:a.id,quantity:qty}]:[]});if(!items.length)return setError("Enter at least one fulfilment quantity.");setSaving(true);setError("");const result=await createTextileDispatch({organizationId:org.id,saleId,dispatchId:makeId(),customerName,deliveryAddress:address,items});setSaving(false);if(result.error)return setError(result.error);setMessage("Dispatch document created. Start picking and scan each physical roll.");setSaleId("");setSelected({});await refresh();}
 async function transition(row:TextileDispatch,next:"picking"|"packed"|"dispatched"|"delivered"|"cancelled"){setSaving(true);setError("");const result=await transitionTextileDispatch(row.id,next,{carrier,vehicleNo,trackingReference:tracking});setSaving(false);if(result.error)return setError(result.error);setMessage(`${row.dispatchNo} moved to ${next}.`);await refresh();}
 async function scan(row:TextileDispatch){const qty=Number(scanQty);if(!scanCode.trim()||qty<=0)return setError("Scan a roll and enter a positive quantity.");setSaving(true);const result=await scanTextileDispatchPick(row.id,scanCode,qty);setSaving(false);if(result.error)return setError(result.error);setScanCode("");setScanQty("");setMessage("Correct roll and quantity confirmed.");await refresh();}
 async function initiateTransfer(){if(!org.id||!canTransfer)return;setSaving(true);const result=await initiateTextileTransfer({organizationId:org.id,transferId:makeId(),rollCode:transferRoll,toLocation});setSaving(false);if(result.error)return setError(result.error);setTransferRoll("");setToLocation("");setMessage("Roll custody is now in transit.");await refresh();}
 async function receiveTransfer(row:TextileTransfer){if(!receiveCode.trim())return setError("Scan the received roll first.");setSaving(true);const result=await receiveTextileTransfer(row.id,receiveCode);setSaving(false);if(result.error)return setError(result.error);setReceiveCode("");setMessage(`${row.transferNo} received at ${row.toLocation}.`);await refresh();}
 async function inspectReturn(row:ReturnHoldRecord){if(!org.id)return;const allocationId=returnAllocation[row.id];const decision=returnDecision[row.id]??"reusable_remnant";const reason=returnReason[row.id]??"";if(!allocationId||!reason.trim())return setError("Original roll allocation and inspection reason are required.");setSaving(true);const result=await inspectTextileReturn({organizationId:org.id,holdId:row.id,saleAllocationId:allocationId,decision,reason,newRollNo:returnRollNo[row.id]});setSaving(false);if(result.error)return setError(result.error);setMessage(`Return ${row.returnNo} inspected with immutable original-roll evidence.`);await refresh();}
 function shareDispatch(row:TextileDispatch){const text=`LakBiz dispatch ${row.dispatchNo} for invoice ${row.saleId} is ${row.status}.${row.trackingReference?` Tracking: ${row.trackingReference}.`:""}`;window.open(`https://wa.me/?text=${encodeURIComponent(text)}`,"_blank","noopener,noreferrer");}
 if(!ready||loading)return <AppShell><ProMain><ProLoadingState label="Loading warehouse operations…"/></ProMain></AppShell>;
 if(org.sector!=="textile")return <AppShell><ProMain><ProEmptyState title="Textile workspace only" description="Roll-aware dispatch is available only for Textile businesses."/></ProMain></AppShell>;
 const openDispatches=dispatches.filter((d)=>!["delivered","cancelled"].includes(d.status));
 return <AppShell><ProMain>
  <ProPageHeader eyebrow="Textile fulfilment" title="Warehouse & dispatch" description="Control sold fabric from pick list to customer delivery. Every physical roll handoff is scan-confirmed and partial fulfilment remains visible." actions={<><ProBadge tone="emerald">Custody ledger</ProBadge><ProButton href="/stock/cutting" variant="secondary">Cutting Desk</ProButton></>}/><WriteDisabledHint className="mb-5"/>
  {error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-800">{error}</div>}{message&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{message}</div>}
  <div className="grid gap-4 sm:grid-cols-3"><ProStatCard label="Open dispatches" value={String(openDispatches.length)} hint="Not delivered or cancelled" tone="teal"/><ProStatCard label="Unfulfilled lines" value={String(allocations.filter((a)=>a.assignedQuantity<a.quantity-.0005).length)} hint="Sold quantity awaiting dispatch" tone="amber"/><ProStatCard label="Rolls in transit" value={String(transfers.filter((t)=>t.status==="in_transit").length)} hint="Location custody handoffs" tone="rose"/></div>
  <div className="my-5 flex flex-wrap gap-2"><button className={tab==="dispatch"?primary:secondary} onClick={()=>setTab("dispatch")}>Pick, pack & dispatch</button><button className={tab==="transfer"?primary:secondary} onClick={()=>setTab("transfer")}>Warehouse transfer</button><button className={tab==="returns"?primary:secondary} onClick={()=>setTab("returns")}>Return inspection</button></div>
  {tab==="dispatch"?<div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
   <ProCard eyebrow="Partial fulfilment" title="Create dispatch document"><div className="space-y-4"><label className={label}>Sale / invoice *<select className={input} value={saleId} onChange={(e)=>{setSaleId(e.target.value);setSelected({});}}><option value="">Select unfulfilled sale</option>{saleIds.map((id)=><option key={id}>{id}</option>)}</select></label>{saleAllocations.map((a)=><label key={a.id} className={label}>{productById.get(a.productId)?.name??"Fabric"} · Roll {a.rollNo}<span className="ml-1 text-slate-400">remaining {(a.quantity-a.assignedQuantity).toFixed(3)} {a.lengthUnit}</span><input type="number" min="0" max={a.quantity-a.assignedQuantity} step="0.001" className={input} value={selected[a.id]??""} onChange={(e)=>setSelected((current)=>({...current,[a.id]:e.target.value}))}/></label>)}<label className={label}>Customer name<input className={input} value={customerName} onChange={(e)=>setCustomerName(e.target.value)}/></label><label className={label}>Delivery address<textarea className={`${input} min-h-20`} value={address} onChange={(e)=>setAddress(e.target.value)}/></label><button className={`${primary} w-full`} disabled={!canOperate||saving||!saleId} onClick={()=>void createDispatch()}>{saving?"Saving…":"Create dispatch"}</button></div></ProCard>
   <ProCard eyebrow="Scan-confirmed queue" title="Open dispatches">{openDispatches.length===0?<ProEmptyState size="compact" title="Dispatch queue is clear" description="Completed cutting allocations can be assigned to a full or partial dispatch."/>:<div className="space-y-4">{openDispatches.map((row)=>{const progress=dispatchProgress(row.items);return <article key={row.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-2"><p className="font-semibold text-slate-950">{row.dispatchNo}</p><ProBadge tone={row.status==="dispatched"?"emerald":row.status==="packed"?"teal":"amber"}>{row.status}</ProBadge></div><p className="mt-1 text-xs text-slate-500">Sale {row.saleId} · {row.customerName||"Customer not named"}</p></div><button className={secondary} onClick={()=>shareDispatch(row)}>WhatsApp update</button></div><div className="mt-3 grid grid-cols-3 gap-2 rounded-xl bg-slate-50 p-3 text-center text-xs"><div><b>{progress.ordered.toFixed(3)}</b><br/>Assigned</div><div><b>{progress.picked.toFixed(3)}</b><br/>Picked</div><div><b>{progress.packed.toFixed(3)}</b><br/>Packed</div></div>
    {row.status==="draft"&&<div className="mt-3 flex gap-2"><button className={primary} disabled={!canOperate||saving} onClick={()=>void transition(row,"picking")}>Start picking</button><button className={secondary} disabled={!canOperate||saving} onClick={()=>void transition(row,"cancelled")}>Cancel</button></div>}
    {row.status==="picking"&&<div className="mt-3 grid gap-3 sm:grid-cols-[1fr_130px_auto]"><label className={label}>Scan roll number / barcode<input className={input} value={activeId===row.id?scanCode:""} onFocus={()=>setActiveId(row.id)} onChange={(e)=>{setActiveId(row.id);setScanCode(e.target.value)}}/></label><label className={label}>Quantity<input type="number" min="0.001" step="0.001" className={input} value={activeId===row.id?scanQty:""} onFocus={()=>setActiveId(row.id)} onChange={(e)=>{setActiveId(row.id);setScanQty(e.target.value)}}/></label><div className="flex items-end gap-2"><button className={primary} disabled={!canOperate||saving} onClick={()=>void scan(row)}>Confirm</button><button className={secondary} disabled={progress.picked<progress.ordered-.0005} onClick={()=>void transition(row,"packed")}>Pack</button></div></div>}
    {row.status==="packed"&&<div className="mt-3 grid gap-3 sm:grid-cols-3"><label className={label}>Carrier<input className={input} value={carrier} onChange={(e)=>setCarrier(e.target.value)}/></label><label className={label}>Vehicle number<input className={input} value={vehicleNo} onChange={(e)=>setVehicleNo(e.target.value)}/></label><label className={label}>Tracking reference<input className={input} value={tracking} onChange={(e)=>setTracking(e.target.value)}/></label><button className={primary} disabled={!canOperate||saving||(!vehicleNo.trim()&&!tracking.trim())} onClick={()=>void transition(row,"dispatched")}>Confirm dispatch</button></div>}
    {row.status==="dispatched"&&<button className={`${primary} mt-3`} disabled={!canOperate||saving} onClick={()=>void transition(row,"delivered")}>Mark delivered</button>}
   </article>})}</div>}</ProCard></div>:
   tab==="transfer"?<div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><ProCard eyebrow="Whole-roll custody" title="Initiate location transfer"><div className="space-y-4"><label className={label}>Scan roll number / barcode *<input className={input} value={transferRoll} onChange={(e)=>setTransferRoll(e.target.value)}/></label><label className={label}>Destination rack / branch *<input className={input} value={toLocation} onChange={(e)=>setToLocation(e.target.value)} placeholder="Branch 02 · Rack B-04"/></label><button className={`${primary} w-full`} disabled={!canTransfer||saving||!transferRoll.trim()||!toLocation.trim()} onClick={()=>void initiateTransfer()}>Start custody transfer</button><p className="text-xs leading-5 text-slate-500">Reserved rolls cannot move. In-transit rolls are blocked from POS until destination scanning confirms receipt.</p></div></ProCard><ProCard eyebrow="Transfer ledger" title="In-transit and received rolls">{transfers.length===0?<ProEmptyState size="compact" title="No roll transfers" description="Scan-based location transfers will appear here."/>:<div className="space-y-3">{transfers.map((row)=><article key={row.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-semibold">{row.transferNo} · Roll {row.rollNo}</p><p className="mt-1 text-xs text-slate-500">{row.fromLocation} → {row.toLocation}</p></div><ProBadge tone={row.status==="received"?"emerald":"amber"}>{row.status.replaceAll("_"," ")}</ProBadge></div>{row.status==="in_transit"&&<div className="mt-3 flex gap-2"><input aria-label="Scan received roll" className={`${input} mt-0`} value={activeId===row.id?receiveCode:""} onFocus={()=>setActiveId(row.id)} onChange={(e)=>{setActiveId(row.id);setReceiveCode(e.target.value)}} placeholder="Scan received roll"/><button className={primary} disabled={!canOperate||saving} onClick={()=>void receiveTransfer(row)}>Receive</button></div>}</article>)}</div>}</ProCard></div>:
   <ProCard eyebrow="Original sale traceability" title="Textile return inspection">{returnHolds.length===0?<ProEmptyState size="compact" title="No Textile returns awaiting inspection" description="Customer return holds created from original invoices appear here."/>:<div className="space-y-4">{returnHolds.map((row)=>{const matching=allocations.filter((a)=>a.saleId===row.saleId&&a.productId===row.productId);const decision=returnDecision[row.id]??"reusable_remnant";return <article key={row.id} className="rounded-2xl border border-slate-200 p-4"><p className="font-semibold text-slate-950">{row.returnNo} · {productById.get(row.productId)?.name??"Fabric"} · {row.qty.toFixed(3)}</p><p className="mt-1 text-xs text-slate-500">Original sale {row.saleId}</p><div className="mt-3 grid gap-3 md:grid-cols-2"><label className={label}>Original sold roll *<select className={input} value={returnAllocation[row.id]??""} onChange={(e)=>setReturnAllocation((v)=>({...v,[row.id]:e.target.value}))}><option value="">Select original allocation</option>{matching.map((a)=><option key={a.id} value={a.id}>Roll {a.rollNo} · {a.quantity.toFixed(3)} {a.lengthUnit}</option>)}</select></label><label className={label}>Inspection decision<select className={input} value={decision} onChange={(e)=>setReturnDecision((v)=>({...v,[row.id]:e.target.value as typeof decision}))}><option value="reusable_remnant">Reusable remnant</option><option value="damaged">Damaged — write off</option><option value="rejected">Rejected — no stock</option></select></label>{decision==="reusable_remnant"&&<label className={label}>New remnant roll number *<input className={input} value={returnRollNo[row.id]??""} onChange={(e)=>setReturnRollNo((v)=>({...v,[row.id]:e.target.value}))}/></label>}<label className={label}>Mandatory inspection reason *<input className={input} value={returnReason[row.id]??""} onChange={(e)=>setReturnReason((v)=>({...v,[row.id]:e.target.value}))}/></label></div><button className={`${primary} mt-3`} disabled={!canTransfer||saving} onClick={()=>void inspectReturn(row)}>Complete inspection</button></article>})}</div>}</ProCard>}
 </ProMain></AppShell>;
}
