from pathlib import Path

p = Path("lakbiz/app/src/app/sales/page.tsx")
s = p.read_text()

def rep(old, new, label):
    global s
    if old not in s:
        raise SystemExit(f"missing {label}")
    s = s.replace(old, new, 1)

rep('import type { PaymentMethod, ProductCondition } from "@/lib/types";', 'import type { PaymentMethod, Product, ProductCondition } from "@/lib/types";', 'Product import')
rep('const ADVANCED_POS_SECTORS = new Set(["pharmacy", "mobile_shop", "electronics", "footwear"]);\n', '''const ADVANCED_POS_SECTORS = new Set(["pharmacy", "mobile_shop", "electronics", "footwear"]);\n\nfunction productSearchText(product: Product): string {\n  return [product.name, product.sku, product.category, product.customFields.barcode, product.customFields.genericName, product.customFields.brand, product.customFields.strength, product.customFields.packSize]\n    .filter(Boolean).map(String).join(" ").toLowerCase();\n}\n''', 'search helper')
rep('  const conditionFilterRelevant = org.sector !== "pharmacy" && org.sector !== "grocery";\n', '  const conditionFilterRelevant = org.sector !== "pharmacy" && org.sector !== "grocery";\n  const fastRetailPos = org.sector === "pharmacy" || org.sector === "grocery";\n', 'fast retail flag')
rep('  const [conditionFilter, setConditionFilter] = useState<ConditionFilter>("all");\n', '  const [conditionFilter, setConditionFilter] = useState<ConditionFilter>("all");\n  const [categoryFilter, setCategoryFilter] = useState("all");\n  const [resultLimit, setResultLimit] = useState(24);\n', 'retail states')
rep('''  const setOverride = (id: string, value: number) => {\n    setPriceOverrides((o) => ({ ...o, [id]: Math.max(0, value) }));\n  };''', '''  const addOneToCart = (product: Product) => {\n    setQty(product.id, (cart[product.id] ?? 0) + 1, product.stockQty);\n    setSearch("");\n    setCategoryFilter("all");\n    setResultLimit(24);\n  };\n\n  const setOverride = (id: string, value: number) => {\n    setPriceOverrides((o) => ({ ...o, [id]: Math.max(0, value) }));\n  };''', 'quick add')
rep('    setSearch("");\n  };\n\n  const buyerName', '    setSearch("");\n    setCategoryFilter("all");\n    setResultLimit(24);\n  };\n\n  const buyerName', 'reset filters')
old = '''  const inStock = data.products.filter((p) => p.stockQty > 0 && p.active);\n  const query = search.trim().toLowerCase();\n  const searched = query\n    ? inStock.filter(\n        (p) =>\n          p.name.toLowerCase().includes(query) ||\n          (p.sku ?? "").toLowerCase().includes(query) ||\n          p.category.toLowerCase().includes(query),\n      )\n    : inStock;\n  const filtered =\n    !conditionFilterRelevant || conditionFilter === "all"\n      ? searched\n      : searched.filter((p) => p.condition === conditionFilter);'''
new = '''  const inStock = data.products.filter((p) => p.stockQty > 0 && p.active);\n  const query = search.trim().toLowerCase();\n  const searched = query ? inStock.filter((p) => productSearchText(p).includes(query)) : inStock;\n  const categoryFiltered = fastRetailPos && categoryFilter !== "all" ? searched.filter((p) => p.category === categoryFilter) : searched;\n  const filtered = !conditionFilterRelevant || conditionFilter === "all" ? categoryFiltered : categoryFiltered.filter((p) => p.condition === conditionFilter);\n  const categoryCounts = new Map<string, number>();\n  if (fastRetailPos) for (const p of inStock) categoryCounts.set(p.category || "General", (categoryCounts.get(p.category || "General") ?? 0) + 1);\n  const fastRetailCategories = Array.from(categoryCounts.entries()).map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count || a.name.localeCompare(b.name)).slice(0, 12);\n  const exactRetailMatch = query ? filtered.find((p) => (p.sku ?? "").trim().toLowerCase() === query || String(p.customFields.barcode ?? "").trim().toLowerCase() === query) : undefined;\n  const quickAddCandidate = exactRetailMatch ?? filtered[0];\n  const visibleProducts = fastRetailPos ? filtered.slice(0, resultLimit) : filtered;'''
rep(old, new, 'filter block')
rep('''                    onChange={(e) => setSearch(e.target.value)}\n                    placeholder={t("sales.search_placeholder")}''', '''                    autoFocus={fastRetailPos}\n                    autoComplete="off"\n                    onChange={(e) => { setSearch(e.target.value); if (fastRetailPos) setResultLimit(24); }}\n                    onKeyDown={(e) => {\n                      if (!fastRetailPos) return;\n                      if (e.key === "Enter" && quickAddCandidate) { e.preventDefault(); addOneToCart(quickAddCandidate); }\n                      if (e.key === "Escape") setSearch("");\n                    }}\n                    placeholder={fastRetailPos ? (org.sector === "pharmacy" ? "Search medicine, generic, brand, code or barcode…" : "Scan barcode or search product, brand or code…") : t("sales.search_placeholder")}''', 'search input')
rep('''                  <span className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">⌕</span>\n                </div>\n                {conditionFilterRelevant && (''', '''                  <span className="pointer-events-none absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">⌕</span>\n                </div>\n                {fastRetailPos && (\n                  <>\n                    <div className="mt-2 flex flex-wrap items-center justify-between gap-2 text-[11px] font-semibold text-slate-500">\n                      <span>{org.sector === "pharmacy" ? "Name · generic · brand · strength · code · barcode" : "Name · brand · code · barcode"}</span>\n                      <span className="rounded-lg bg-slate-100 px-2 py-1 text-slate-600">Enter adds first match · Esc clears</span>\n                    </div>\n                    <div className="mt-3 flex gap-2 overflow-x-auto pb-1 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">\n                      <button type="button" onClick={() => { setCategoryFilter("all"); setResultLimit(24); }} className={`shrink-0 rounded-xl px-3 py-2 text-xs font-bold ${categoryFilter === "all" ? "bg-teal-600 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>All <span className="opacity-70">{inStock.length}</span></button>\n                      {fastRetailCategories.map((category) => (\n                        <button key={category.name} type="button" onClick={() => { setCategoryFilter(category.name); setResultLimit(24); }} className={`shrink-0 rounded-xl px-3 py-2 text-xs font-bold ${categoryFilter === category.name ? "bg-teal-600 text-white" : "border border-slate-200 bg-white text-slate-600"}`}>{category.name} <span className="opacity-70">{category.count}</span></button>\n                      ))}\n                    </div>\n                  </>\n                )}\n                {conditionFilterRelevant && (''', 'category strip')
rep('                <div className="grid gap-3 md:grid-cols-2">\n                  {filtered.map((p) => {', '                <div className={fastRetailPos ? "grid gap-2 md:grid-cols-2 2xl:grid-cols-3" : "grid gap-3 md:grid-cols-2"}>\n                  {visibleProducts.map((p) => {', 'limited product grid')
rep('''                            <p className="mt-1 text-xs font-semibold text-slate-500">\n                              {p.sku ? `${p.sku} · ` : ""}{p.category || "General"}\n                            </p>''', '''                            <p className="mt-1 text-xs font-semibold text-slate-500">\n                              {p.sku ? `${p.sku} · ` : ""}{p.category || "General"}\n                            </p>\n                            {org.sector === "pharmacy" && (\n                              <p className="mt-1 line-clamp-1 text-[11px] font-medium text-slate-500">{[p.customFields.genericName, p.customFields.strength, p.customFields.brand, p.customFields.packSize].filter(Boolean).map(String).join(" · ") || "Batch-controlled stock"}</p>\n                            )}''', 'pharmacy metadata')
rep('''                    );\n                  })}\n                </div>\n              )}\n            </div>''', '''                    );\n                  })}\n                  {fastRetailPos && filtered.length > visibleProducts.length && (\n                    <button type="button" onClick={() => setResultLimit((n) => n + 24)} className="min-h-24 rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-4 text-left hover:border-teal-300 hover:bg-teal-50">\n                      <span className="block text-sm font-bold text-slate-800">Show more products</span>\n                      <span className="mt-1 block text-xs text-slate-500">Showing {visibleProducts.length} of {filtered.length}. Search or choose a category for faster access.</span>\n                    </button>\n                  )}\n                </div>\n              )}\n            </div>''', 'show more')
p.write_text(s)

p = Path("lakbiz/app/src/components/dashboard/retail-command-center.tsx")
s = p.read_text().replace('pharmacyEyebrow: "Pharmacy operations"', 'pharmacyEyebrow: "Operations workspace"', 1).replace('groceryEyebrow: "Retail command center"', 'groceryEyebrow: "Operations workspace"', 1)
p.write_text(s)
