import {
  DashboardIcon,
  SalesIcon,
  BillsIcon,
  CustomersIcon,
  StockIcon,
  SuppliersIcon,
  VehiclesIcon,
  JobsIcon,
  AssetIcon,
  CrewIcon,
  WorkforceIcon,
  BankingIcon,
  VatIcon,
  TeamIcon,
  PlansIcon,
  BellIcon,
  ShopIcon,
  CalendarIcon,
  CostingIcon,
  ExpenseIcon,
  ReportsIcon,
  type IconProps,
} from "@/components/ui/icons";

/** href -> icon, shared by Sidebar and MobileNav so the two stay in sync. */
export const NAV_ICON_BY_HREF: Record<string, (props: IconProps) => React.ReactElement> = {
  "/dashboard": DashboardIcon,
  "/sales": SalesIcon,
  "/bills": BillsIcon,
  "/customers": CustomersIcon,
  "/stock": StockIcon,
  "/suppliers": SuppliersIcon,
  "/vehicles": VehiclesIcon,
  "/jobs": JobsIcon,
  "/schedule": CalendarIcon,
  "/assets": AssetIcon,
  "/teams": CrewIcon,
  "/workforce": WorkforceIcon,
  "/banking": BankingIcon,
  "/vat": VatIcon,
  "/expenses": ExpenseIcon,
  "/job-costing": CostingIcon,
  "/reports": ReportsIcon,
  "/settings/team": TeamIcon,
  "/settings/plans": PlansIcon,
  "/settings/notifications": BellIcon,
  "/settings/shop": ShopIcon,
};
