"use client";import{createBrowserClient}from"@/lib/supabase/client";
export type UnitStock={length_unit:"metre"|"yard";active_rolls:number;remaining:number;reserved:number;damaged:number;remnants:number;stock_value_lkr:number|null;costed_quantity:number;uncosted_quantity:number};
export type ChannelPerformance={sale_mode:string;length_unit:"metre"|"yard";quantity:number;revenue_lkr:number;known_cost_lkr:number|null;known_margin_lkr:number|null;uncosted_quantity:number};
export type RollAgeing={id:string;roll_no:string;product_id:string;length_unit:"metre"|"yard";remaining_length:number;is_remnant:boolean;rack_location:string|null;age_days:number;value_lkr:number|null;age_band:string};
export type SlowRoll={id:string;roll_no:string;product_id:string;length_unit:"metre"|"yard";remaining_length:number;rack_location:string|null;age_days:number;last_sale_date:string|null;value_lkr:number|null};
export type LocationStock={location:string;length_unit:"metre"|"yard";rolls:number;remaining:number;value_lkr:number|null};
export type WasteMetric={length_unit:"metre"|"yard";planned_cut:number;waste:number;waste_percent:number;waste_events:number};
export type TextileOwnerIntelligence={generated_at:string;period_from:string;period_to:string;stock_by_unit:UnitStock[];channel_performance:ChannelPerformance[];roll_ageing:RollAgeing[];slow_moving:SlowRoll[];locations:LocationStock[];cutting_waste:WasteMetric[];receivables:{open_total:number;overdue_total:number;current:number;days_1_30:number;days_31_60:number;days_61_90:number;days_90_plus:number};scheduled_inflows:{receivables_due_7d:number;receivables_due_30d:number;cheques_due_7d:number;cheques_due_30d:number};quality_events:{measurement_adjustments:number;measurement_variance:number;damage_movements:number;return_movements:number;transfer_movements:number}};
export type TextileAuditSnapshot={id:string;periodFrom:string;periodTo:string;createdAt:string};
export async function fetchTextileOwnerIntelligence(organizationId:string,from:string,to:string){const supabase=createBrowserClient();if(!supabase)return{data:null as TextileOwnerIntelligence|null,error:"Supabase not configured"};const{data,error}=await supabase.rpc("get_textile_owner_intelligence",{p_organization_id:organizationId,p_from:from,p_to:to});return{data:error?null:data as TextileOwnerIntelligence,error:error?.message??null};}
export async function fetchTextileAuditSnapshots(organizationId:string){const supabase=createBrowserClient();if(!supabase)return{data:[] as TextileAuditSnapshot[],error:"Supabase not configured"};const{data,error}=await supabase.from("textile_audit_snapshots").select("id,period_from,period_to,created_at").eq("organization_id",organizationId).order("created_at",{ascending:false}).limit(20);return{data:(data??[]).map(x=>({id:String(x.id),periodFrom:String(x.period_from),periodTo:String(x.period_to),createdAt:String(x.created_at)})),error:error?.message??null};}
export async function captureTextileAuditSnapshot(organizationId:string,from:string,to:string){const supabase=createBrowserClient();if(!supabase)return{error:"Supabase not configured"};const{error}=await supabase.rpc("capture_textile_audit_snapshot",{p_organization_id:organizationId,p_from:from,p_to:to});return{error:error?.message??null};}
