"use client";
import { createBrowserClient } from "@/lib/supabase/client";

export type TextileReceivable={id:string;saleId:string;customerId:string;originalAmount:number;outstandingAmount:number;invoiceDate:string;dueDate:string;source:string;status:string};
export type TextileCustomerTerms={customerId:string;paymentTermsDays:number;creditHold:boolean;holdReason:string|null};
export type TextileSupplierPrice={id:string;supplierId:string;productId:string;currency:string;unitPrice:number;fxRateLkr:number;minQuantity:number;leadTimeDays:number|null;quotedAt:string;validUntil:string|null;reference:string|null};
export type TextileImportShipment={id:string;shipmentNo:string;containerNo:string|null;supplierId:string|null;originCountry:string|null;currency:string;fxRateLkr:number;freightLkr:number;dutyLkr:number;insuranceLkr:number;portLkr:number;handlingLkr:number;eta:string|null;status:string};
export type TextileCommissionPolicy={id:string;salespersonUserId:string;basis:"collected_revenue"|"approved_margin";ratePercent:number;effectiveFrom:string;active:boolean};
export type TextileCommissionEntry={id:string;salespersonUserId:string;saleId:string;eligibleBase:number;commissionAmount:number;status:string;evidenceType:string;createdAt:string};

export async function fetchTextileTradeControl(organizationId:string){const supabase=createBrowserClient();if(!supabase)return{data:null,error:"Supabase not configured"};const[r,t,p,s,cp,ce,m]=await Promise.all([
 supabase.from("textile_receivables").select("*").eq("organization_id",organizationId).order("due_date"),supabase.from("textile_customer_terms").select("*").eq("organization_id",organizationId),supabase.from("textile_supplier_prices").select("*").eq("organization_id",organizationId).order("quoted_at",{ascending:false}),supabase.from("textile_import_shipments").select("*").eq("organization_id",organizationId).order("created_at",{ascending:false}),supabase.from("textile_commission_policies").select("*").eq("organization_id",organizationId).order("effective_from",{ascending:false}),supabase.from("textile_commission_entries").select("*").eq("organization_id",organizationId).order("created_at",{ascending:false}),supabase.from("org_members").select("user_id,role").eq("organization_id",organizationId)
]);const error=r.error||t.error||p.error||s.error||cp.error||ce.error||m.error;if(error)return{data:null,error:error.message};return{data:{receivables:(r.data??[]).map(x=>({id:String(x.id),saleId:String(x.sale_id),customerId:String(x.customer_id),originalAmount:Number(x.original_amount),outstandingAmount:Number(x.outstanding_amount),invoiceDate:String(x.invoice_date),dueDate:String(x.due_date),source:String(x.source),status:String(x.status)})) as TextileReceivable[],terms:(t.data??[]).map(x=>({customerId:String(x.customer_id),paymentTermsDays:Number(x.payment_terms_days),creditHold:Boolean(x.credit_hold),holdReason:x.hold_reason?String(x.hold_reason):null})) as TextileCustomerTerms[],supplierPrices:(p.data??[]).map(x=>({id:String(x.id),supplierId:String(x.supplier_id),productId:String(x.product_id),currency:String(x.currency),unitPrice:Number(x.unit_price),fxRateLkr:Number(x.fx_rate_lkr),minQuantity:Number(x.min_quantity),leadTimeDays:x.lead_time_days==null?null:Number(x.lead_time_days),quotedAt:String(x.quoted_at),validUntil:x.valid_until?String(x.valid_until):null,reference:x.reference?String(x.reference):null})) as TextileSupplierPrice[],shipments:(s.data??[]).map(x=>({id:String(x.id),shipmentNo:String(x.shipment_no),containerNo:x.container_no?String(x.container_no):null,supplierId:x.supplier_id?String(x.supplier_id):null,originCountry:x.origin_country?String(x.origin_country):null,currency:String(x.currency),fxRateLkr:Number(x.fx_rate_lkr),freightLkr:Number(x.freight_lkr),dutyLkr:Number(x.duty_lkr),insuranceLkr:Number(x.insurance_lkr),portLkr:Number(x.port_lkr),handlingLkr:Number(x.handling_lkr),eta:x.eta?String(x.eta):null,status:String(x.status)})) as TextileImportShipment[],policies:(cp.data??[]).map(x=>({id:String(x.id),salespersonUserId:String(x.salesperson_user_id),basis:String(x.basis) as TextileCommissionPolicy["basis"],ratePercent:Number(x.rate_percent),effectiveFrom:String(x.effective_from),active:Boolean(x.active)})) as TextileCommissionPolicy[],entries:(ce.data??[]).map(x=>({id:String(x.id),salespersonUserId:String(x.salesperson_user_id),saleId:String(x.sale_id),eligibleBase:Number(x.eligible_base),commissionAmount:Number(x.commission_amount),status:String(x.status),evidenceType:String(x.evidence_type),createdAt:String(x.created_at)})) as TextileCommissionEntry[],members:(m.data??[]).map(x=>({userId:String(x.user_id),role:String(x.role)}))},error:null};}
const rpc=async(name:string,args:Record<string,unknown>)=>{const supabase=createBrowserClient();if(!supabase)return{error:"Supabase not configured"};const{data,error}=await supabase.rpc(name,args);return{data,error:error?.message??null};};
export const setTextileCustomerTerms=(x:{organizationId:string;customerId:string;paymentTermsDays:number;creditLimit:number;creditHold:boolean;holdReason?:string})=>rpc("set_textile_customer_terms",{p_organization_id:x.organizationId,p_customer_id:x.customerId,p_payment_terms_days:x.paymentTermsDays,p_credit_limit:x.creditLimit,p_credit_hold:x.creditHold,p_hold_reason:x.holdReason?.trim()||null});
export const recordTextileCollection=(x:{organizationId:string;customerId:string;actionType:string;note:string;promiseDate?:string;promiseAmount?:number})=>rpc("record_textile_collection_action",{p_organization_id:x.organizationId,p_customer_id:x.customerId,p_action_type:x.actionType,p_note:x.note,p_promise_date:x.promiseDate||null,p_promise_amount:x.promiseAmount??null});
export const allocateTextilePayment=(organizationId:string,paymentId:string)=>rpc("allocate_textile_customer_payment",{p_organization_id:organizationId,p_customer_payment_id:paymentId});
export const transitionTextileCheque=(organizationId:string,chequeId:string,status:string)=>rpc("transition_textile_cheque",{p_organization_id:organizationId,p_cheque_id:chequeId,p_next_status:status});
export const addTextileSupplierPrice=(x:{organizationId:string;supplierId:string;productId:string;currency:string;unitPrice:number;fxRate:number;minQuantity:number;leadTimeDays:number;validUntil?:string;reference?:string})=>rpc("add_textile_supplier_price",{p_organization_id:x.organizationId,p_supplier_id:x.supplierId,p_product_id:x.productId,p_currency:x.currency,p_unit_price:x.unitPrice,p_fx_rate_lkr:x.fxRate,p_min_quantity:x.minQuantity,p_lead_time_days:x.leadTimeDays,p_valid_until:x.validUntil||null,p_reference:x.reference?.trim()||null});
export const createTextileImport=(x:{organizationId:string;id:string;shipmentNo:string;containerNo?:string;supplierId?:string;origin?:string;currency:string;fxRate:number;freight:number;duty:number;insurance:number;port:number;handling:number;eta?:string})=>rpc("create_textile_import_shipment",{p_organization_id:x.organizationId,p_shipment_id:x.id,p_shipment_no:x.shipmentNo,p_container_no:x.containerNo||null,p_supplier_id:x.supplierId||null,p_origin_country:x.origin||null,p_currency:x.currency,p_fx_rate:x.fxRate,p_freight:x.freight,p_duty:x.duty,p_insurance:x.insurance,p_port:x.port,p_handling:x.handling,p_eta:x.eta||null});
export const addTextileImportRoll=(organizationId:string,shipmentId:string,rollId:string,supplierValueLkr:number)=>rpc("add_textile_import_roll",{p_organization_id:organizationId,p_shipment_id:shipmentId,p_roll_id:rollId,p_supplier_value_lkr:supplierValueLkr});
export const finalizeTextileImport=(organizationId:string,shipmentId:string)=>rpc("finalize_textile_import_cost",{p_organization_id:organizationId,p_shipment_id:shipmentId});
export const setTextileCommissionPolicy=(x:{organizationId:string;userId:string;basis:string;rate:number;effectiveFrom:string})=>rpc("set_textile_commission_policy",{p_organization_id:x.organizationId,p_salesperson_user_id:x.userId,p_basis:x.basis,p_rate:x.rate,p_effective_from:x.effectiveFrom});
export const approveTextileMarginCommission=(organizationId:string,saleId:string,margin:number)=>rpc("approve_textile_margin_commission",{p_organization_id:organizationId,p_sale_id:saleId,p_approved_margin:margin});
